# Generated by Django 4.1 on 2022-11-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_livro_categoria_livro_editora"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="autores",
            field=models.ManyToManyField(related_name="livros", to="core.autor"),
        ),
    ]
